name: JMeter Performance Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  performance-test:
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run JMeter Test
        run: C:\Users\jagannadham.a\Desktop\Jagan\PerformanceTest\run_test.bat

      - name: Upload JMeter HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: JMeter-Report
          path: C:\Users\jagannadham.a\Desktop\Jagan\PerformanceTest\JMeterTest\results\html-report
